name: sonanceep_sns
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.2
  firebase_core: ^2.30.1  # firebase_core: ^2.11.0
  firebase_auth: ^4.19.4  # firebase_auth: ^4.4.0
  cloud_firestore: ^4.8.2
  firebase_analytics: ^10.10.4  # firebase_analytics: ^10.2.0
  google_fonts: ^4.0.3
  pull_to_refresh: ^2.0.0
  image_cropper: ^1.4.1  # image_cropper: ^3.0.3
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10
  clipboard: ^0.1.3
  flutter_launcher_icons: ^0.13.1  # flutter_launcher_icons: ^0.12.0
  flash: ^3.0.5  # flash: ^2.0.3+3
  uuid: ^3.0.7
  provider: ^6.0.5
  image_picker: ^1.0.4  # image_picker: ^0.8.7+1
  video_player: ^2.7.0
  path_provider: ^2.1.1
  chewie: ^1.7.0
  flutter_svg: ^2.0.4
  firebase_storage: ^11.7.4  # firebase_storage: ^11.1.0
  firebase_crashlytics: ^3.5.4  # firebase_crashlytics: ^3.3.3
  fluttertoast: ^8.2.1
  intl: ^0.19.0
  freezed_annotation: ^2.2.0
  material_floating_search_bar_2: ^0.5.0  # material_floating_search_bar: ^0.3.7
  http: ^0.13.6  # http: ^0.13.5
  dio: ^5.3.3
  flutter_dotenv: ^5.1.0
  algolia: ^1.1.2
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.20.2  # flutter_hooks: ^0.18.6
  grpc: ^3.2.4
  protoc_plugin: ^21.1.1
  sliding_up_panel: ^2.0.0+1  # trackに使用
  linked_scroll_controller: ^0.2.0
  file_picker: ^5.5.0  # スマホ内のファイルを取得
  flutter_xlider: ^3.5.0  # trackに使用
  # carousel_slider: ^4.2.1
  # flutter_sound: ^9.2.13
  camera: ^0.10.5
  image_gallery_saver: ^2.0.3  # 画像や動画をギャラリーに保存
  just_audio: ^0.9.35  # データベースから音声ファイルを取得
  audio_wave: ^0.1.5  # 音声ファイルの波形を表示
  soundpool: ^2.3.0  # クリック等の効果音に向いている
  # audioplayers: ^5.2.1
  dropdown_button2: ^2.3.9  # 選択
  audio_waveforms: ^1.0.4
  decorated_icon: ^1.2.1
  visibility_detector: ^0.4.0+2  # ウィジェットの可視性を検出
  ffmpeg_kit_flutter: ^6.0.3  # FFmpegを使用するため

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/audios/accentClick.wav
    - assets/audios/click.wav

  fonts:
    - family: MyFlutterIcons #アイコンセットのタイトル
      fonts:
        - asset: assets/MyFlutterIcons/fonts/MyFlutterIcons.ttf #設置したファイル

















# name: sonanceep_sns
# description: A new Flutter project.

# publish_to: 'none'

# version: 1.0.0+1

# environment:
#   sdk: '>=2.19.5 <3.0.0'

# dependencies:
#   flutter:
#     sdk: flutter

#   cupertino_icons: ^1.0.2
#   flutter_riverpod: ^2.3.2
#   firebase_core: ^2.11.0
#   firebase_auth: ^4.4.0
#   cloud_firestore: ^4.8.2
#   firebase_analytics: ^10.2.0
#   google_fonts: ^4.0.3
#   pull_to_refresh: ^2.0.0
#   image_cropper: ^1.4.1  # image_cropper: ^3.0.3
#   shared_preferences: ^2.1.0
#   url_launcher: ^6.1.10
#   clipboard: ^0.1.3
#   flutter_launcher_icons: ^0.12.0
#   flash: ^3.0.5+1  # flash: ^2.0.3+3
#   uuid: ^3.0.7
#   image_picker: ^0.8.7+1
#   video_player: ^2.7.0
#   chewie: ^1.7.0
#   just_audio: ^0.9.32
#   flutter_svg: ^2.0.4
#   firebase_storage: ^11.2.6  # firebase_storage: ^11.1.0
#   firebase_crashlytics: ^3.3.5  # firebase_crashlytics: ^3.3.3
#   fluttertoast: ^8.2.1
#   intl: ^0.18.1
#   freezed_annotation: ^2.2.0
#   material_floating_search_bar: ^0.3.7
#   http: ^0.13.5
#   flutter_dotenv: ^5.1.0
#   algolia: ^1.1.2
#   hooks_riverpod: ^2.3.6
#   flutter_hooks: ^0.18.6

#   flutter_localizations:
#     sdk: flutter

# dev_dependencies:
#   freezed: ^2.3.2
#   json_serializable: ^6.6.1
#   build_runner: ^2.3.3
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^2.0.0

# flutter:
#   generate: true
#   uses-material-design: true

#   assets:
#    - .env